TEST_DIR = '/home/joente/workspace/testdir'
SIRIDBC = '/home/joente/workspace/siridbc/Debug/siridbc'
MANAGE = '/home/joente/workspace/siridb/manage/manage.py'
PY_SIRIDB_PATH = '/home/joente/workspace/siridb/'
_VALGRIND = 'valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -v '
VALGRIND = 'valgrind --tool=memcheck '