TEST_DIR = '/home/joente/workspace/testdir'
SIRIDBC = '/home/joente/workspace/siridbc/Release/siridbc'
MANAGE = '/home/joente/workspace/siridb/manage/manage.py'
PY_SIRIDB_PATH = '/home/joente/workspace/siridb/'
VALGRIND = 'valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes -v '
_VALGRIND = 'valgrind --tool=memcheck '